<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USGURNGALHOTRA7" ignored="0" name="Trial" tests="6" failures="1" timestamp="2020-12-27T18:02:34 IST" time="97.311" errors="0">
  <testcase name="loginTest" time="25.321" classname="com.trial.testCases.TC_LoginTest_001"/>
  <testcase name="LoginDDT" time="11.784" classname="com.trial.testCases.TC_LoginTest_002"/>
  <testcase name="LoginDDT" time="5.503" classname="com.trial.testCases.TC_LoginTest_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.trial.testCases.TC_LoginTest_002.LoginDDT(TC_LoginTest_002.java:31)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
  <testcase name="LoginDDT" time="10.645" classname="com.trial.testCases.TC_LoginTest_002"/>
  <testcase name="LoginDDT" time="9.278" classname="com.trial.testCases.TC_LoginTest_002"/>
  <testcase name="addNewCustomer" time="15.382" classname="com.trial.testCases.TC_AddCustomerTest_003"/>
</testsuite> <!-- Trial -->
